### ISSUE TITLE
Road map UNDP

### ISSUE THREAD

**Issue by fxi** [fxi/map-x-mgl#212]
### Major / breaking changes

**MAY DEADLINE (test by end of april)**
- [x] Convert country based approach to management by project
- [x] "projects" as uppermost layer for data management but still keep "countries" and apply roles to the combination of both of them if possible (e.g: a user has a certain role for data tagged with a certain project in a certain country. If he enters another country he is a simple user).
- [x] Create "Member" role with "self" editing and deliting rights, "member" and "publisher" writing rights or something more complex depending on you @fxi.
- [x] Create "Project" field in the configuration of views and source layers too. The field should be not accessible for users with no specific project roles. The available projects in the field are those where the users have a specific project role.

**DECEMBER DEADLINE**
- [ ] Temporary multiple layer overlap. GeoCompo : Composite views {Active views on map are overlapped if a button is clicked. When the button is activated, it changes color to show that it is active. The button can be located on the top-side of the map. When the list of active views changes the overlap is updated. The overlap is on map until the button is clicked back).
- [x] Export in different projection systems.
- [ ] Have an improved pdf to export for reporting (contains title, legend, north arrow, scale bar, basic metadata (To be defined: maybe source name, source url, temporal range?. issuance?, contact name and email?) #234
- [ ] Monitor user interaction with platform (at least traffic per project; 2nd priority is for example number of hits, user requests, resource consumption client/server side, views visited and average time of visit, etc.).
- [ ] Data integrity bar next to views' name on the basis of the DIAF score (color graded bar showing percentage score - clickable to reveal the full outcomes of the assessment framework).
- [ ] Friction reduction: Do not allow to create "public" views based on source layers in case:
1) at least one of the following metadata fields of the source layer empty ("Title", "Abstract", "Keywords", "Attributes", all from "Issuance", all from "Contacts", all from "Source", all from "licensing");
2) the answer to at least one of the questions 1,2,3 of the DIAF is [0 or 1].
- [x] Add DB access for user's own sources ***QGIS temporary user***
- [x] Export in CSV format
- [x] Multiple layer query function extended to WMS layers.

### Minor changes
- [x] Null value styling: set optional
- [x] View filtering: or within, and between  
- [x] Sort views in panel by "last updated", "alphabetical order" 

TO BE DEFINED:
- [ ] A solution for showing changes in data integrity over time on the DIAF graded bar.

**Comment by antobenve** [comment]
This issue is closed and re-formulated in #370

**Comment by antobenve** [comment]
@fxi I can't close this issue. Please do it so we can continue in #370.

**Comment by PierreLacroix** [comment]
Now in https://github.com/fxi/map-x-mgl/issues/370. Can be closed
