### ISSUE TITLE
Road map UNDP_new

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#370]
#### DECEMBER DEADLINE
- [x] Temporary multiple layer overlap. GeoCompo : Composite views {Active views on map are overlapped if a button is clicked. When the button is activated, it changes color to show that it is active. The button can be located on the top-side of the map. When the list of active views changes the overlap is updated. The overlap is on map until the button is clicked back).
- [x] Export in different projection systems.
- [x] Have an improved pdf to export for reporting (contains title, legend, north arrow, scale bar, basic metadata (To be defined: maybe source name, source url, temporal range?. issuance?, contact name and email?) #234
- [x] Produce a log of user and projects' related information that can be used for producing stats through sql requests. The tool should be used for monitoring user interaction with platform at project scale. Defined stats include:

> cumulated time during which a view is active
> number of hits of a view
> cumulated time during which a project is open
> number of unique users visiting a project
> number of downloads of a source layer
> region where users connect to a project (probably for the future)

- [x] Automatic publication of **vector** data into GeoServer. Depending on their status (WMS authorized; or WMS+WFS authorized) data should be redirected to one or another workspace in GeoServer. One checkbox for authorizing WMS and one checkbox for authorizing WMS+WFS. A third checkbox to authorize download or not from MapX
- [x] Data integrity bar next to views' name on the basis of the DIAF score (color graded bar showing percentage score - clickable to reveal the full outcomes of the assessment framework). Replace figures (0-1-2-3) with relevant text
- [x] Friction reduction: Apply 1) a red-flag next to the title of a view and 2) mouseover text "The metadata of the source layer associated to this view are not properly compiled." if any of the following conditions are matched:

For vector type views (check mx_sources)

> Any of the following fields were not yet generated in mx_sources,
> "Abstract" is empty,
> "Keywords" is empty,
> At least one subfield of "Attributes"  is empty,
> Every subfield of "Issuance"  is empty,
> Every subfield of "Contacts"  is empty,
> At least one subfield of "Source" is empty,
> At least one subfield from "licensing" is empty.

For raster type views (check mx_views --> 'sources, urlMetadata')

> The field "Link to the metadata" is empty or it doesn't exist.

- [x] Add DB access for user's own sources QGIS temporary user
- [x] Export in CSV format
- [x] Multiple layer query function extended to WMS layers.

#### Minor changes
- [x]  Null value styling: set optional
- [x]  View filtering: or within, and between
- [x]  Sort views in panel by "last updated", "alphabetical order"

**Comment by antobenve** [comment]
This issue is closed as the results were accomplished.
